const Questions = [
  // Easy
  {
    id: 1,
    Ques: "Which of the following data structures is non-linear? (multi-choice)",
    quesImage: "",
    codeBlock: "",
    type: "prog",
    level: "easy",
    options: [
      { id: "1", option: "Stack" },
      { id: "2", option: "Array" },
      { id: "3", option: "Graph" },
      { id: "4", option: "Linked List" },
      { id: "5", option: "Tree" },
    ],
    answer: [{ id: "3" }, { id: "5" }],
    isMultiSelect: true,
  },
  {
    id: 2,
    Ques: "Which of the following series will be printed by the given pseudocode?",
    quesImage: "",
    codeBlock: `
  Integer a, b, c
  Set b = 4, c = 5
  for(each a from 2 to b)
    print c
    b = b - 1
    c = c + b
  End loop
    `,
    type: "prog",
    level: "hard",
    options: [
      { id: "1", option: "5 8 10" },
      { id: "2", option: "5 8 10 11" },
      { id: "3", option: "Infinite" },
      { id: "4", option: "5 8" },
    ],
    answer: [{ id: "1" }],
    isMultiSelect: false,
  },
  {
    id: 3,
    Ques: "Which of the following statement is correct to display all the cities with the condition, temperature, and humidity whose humidity is in the range of 60 to 75 from the 'weather' table? (multichoice)",
    quesImage: "",
    codeBlock: "",
    type: "prog",
    level: "hard",
    options: [
      { id: "1", option: "SELECT * FROM weather WHERE humidity IN (60 to 75)" },
      {
        id: "2",
        option: "SELECT * FROM weather WHERE humidity BETWEEN 60 AND 75",
      },
      {
        id: "3",
        option: "SELECT * FROM weather WHERE humidity NOT IN (60 AND 75)",
      },
      {
        id: "4",
        option: "SELECT * FROM weather WHERE humidity NOT BETWEEN 60 AND 75",
      },
      {
        id: "5",
        option: "SELECT * FROM weather WHERE humidity >= 60 or humidity <= 75",
      },
      {
        id: "6",
        option: "SELECT * FROM weather WHERE humidity >= 60 AND humidity <= 75",
      },
    ],
    answer: [{ id: "2" }, { id: "6" }],
    isMultiSelect: true,
  },
  {
    id: 4,
    Ques: "Guess the output of this javascript code?",
    quesImage: "",
    codeBlock: `
  let x = [1, 2, 3];
  let y = [1, 2, 3];
  let z = y;
  
  console.log(x == y);
  console.log(x === y);
  console.log(z == y);
  console.log(z == x);
    `,
    type: "prog",
    level: "easy",
    options: [
      { id: "1", option: "false false true false" },
      { id: "2", option: "false false false false" },
      { id: "3", option: "true true false true" },
      { id: "4", option: "false true false true" },
    ],
    answer: [{ id: "1" }],
    isMultiSelect: false,
  },
  {
    id: 5,
    Ques: "Guess the output?",
    quesImage: "",
    codeBlock: `
  const arr = [1, 2, 3];
  arr.shift();
  console.log(arr);
    `,
    type: "prog",
    level: "easy",
    options: [
      { id: "1", option: "[2, 3]" },
      { id: "2", option: "[1, 2]" },
      { id: "3", option: "[3]" },
      { id: "4", option: "[2, 3, 1]" },
    ],
    answer: [{ id: "1" }],
    isMultiSelect: false,
  },
  {
    id: 6,
    Ques: "What is the worst-case time complexity of searching for an element in an unbalanced binary search tree (BST)?",
    quesImage: "",
    codeBlock: "",
    type: "prog",
    level: "medium",
    options: [
      { id: "1", option: "O(1)" },
      { id: "2", option: "O(log n)" },
      { id: "3", option: "O(n)" },
      { id: "4", option: "O(n log n)" },
    ],
    answer: [{ id: "3" }],
    isMultiSelect: false,
  },
  {
    id: 7,
    Ques: "Which of the following is true about a class in Object-Oriented Programming?",
    quesImage: "",
    codeBlock: "",
    type: "prog",
    level: "medium",
    options: [
      {
        id: "1",
        option: "A class defines the behavior and attributes of an object.",
      },
      { id: "2", option: "A class is a type of object." },
      { id: "3", option: "A class is a structure that stores data." },
      { id: "4", option: "None of the above." },
    ],
    answer: [{ id: "1" }],
    isMultiSelect: false,
  },
  {
    id: 8,
    Ques: "What will be the output of the program?",
    quesImage: "",
    codeBlock: `
  n = 999
  print(n & 1)
    `,
    type: "prog",
    level: "hard",
    options: [
      { id: "1", option: "1" },
      { id: "2", option: "0" },
      { id: "3", option: "999" },
      { id: "4", option: "undefined" },
      { id: "5", option: "Syntax Error" },
    ],
    answer: [{ id: "1" }],
    isMultiSelect: false,
  },
  {
    id: 9,
    Ques: "What will be the output of the following code?",
    quesImage: "",
    codeBlock: `
  a = 10
  const foo() {
      a = 5
      print(a)
  }
  foo()
  print(a)
    `,
    type: "prog",
    level: "easy",
    options: [
      { id: "1", option: "5 5" },
      { id: "2", option: "5 10" },
      { id: "3", option: "10 5" },
      { id: "4", option: "10 10" },
    ],
    answer: [{ id: "2" }],
    isMultiSelect: false,
  },
  {
    id: 10,
    Ques: "What is the difference between forEach() and map()?",
    quesImage: "",
    codeBlock: "",
    type: "prog",
    level: "easy",
    options: [
      {
        id: "1",
        option: "map() modifies the original array, while forEach() does not.",
      },
      {
        id: "2",
        option: "forEach() returns a new array, while map() does not.",
      },
      {
        id: "3",
        option: "map() returns a new array, while forEach() does not.",
      },
      { id: "4", option: "There is no difference." },
    ],
    answer: [{ id: "3" }],
    isMultiSelect: false,
  },
  {
    id: 11,
    Ques: "What will be the output of the following Python program?",
    quesImage: "",
    codeBlock: `
  def func(s):
      r_s = ""
      i = len(s) - 1
      while i >= 0:
          r_s += s[i+1]
          i = i-1
      return r_s
  
  # Call the function
  print(func("hello"))
    `,
    type: "prog",
    level: "hard",
    options: [
      { id: "1", option: "olleh" },
      { id: "2", option: "Index out of range" },
      { id: "3", option: "lleho" },
      { id: "4", option: "syntax error" },
    ],
    answer: [{ id: "2" }],
    isMultiSelect: false,
  },
  {
    id: 12,
    Ques: "What will be the output of the following Python program?",
    quesImage: "",
    codeBlock: `
  a = "HELLO"
  b = a
  a += " WORLD"
  print(b)
    `,
    type: "prog",
    level: "hard",
    options: [
      { id: "1", option: "HELLO" },
      { id: "2", option: "HELLO WORLD" },
      { id: "3", option: "WORLD" },
      { id: "4", option: "HELLOWORLD" },
    ],
    answer: [{ id: "1" }],
    isMultiSelect: false,
  },
  // {
  //   id: 2,
  //   Ques: "Which language is used for styling web pages?",
  //   quesImage: "",
  //   codeBlock: `
  //   my_list = ['Multiple of 6' if i % 6 == 0
  //              else 'Multiple of 2' if i % 2 == 0
  //              else 'Multiple of 3' if i % 3 == 0
  //              else i for i in range(1, 20)]
  //   print(my_list)
  //       `,
  //   type: "prog",
  //   level: "easy",
  //   options: [
  //     { id: "1", option: "HTML" },
  //     { id: "2", option: "CSS" },
  //   ],
  //   answer: [{ id: "2" }],
  //   isMultiSelect: false,
  // },
  // {
  //   id: 3,
  //   Ques: "What does the `console.log()` function do?",
  //   quesImage: "",
  //   codeBlock: `
  //   my_list = ['Multiple of 6' if i % 6 == 0
  //              else 'Multiple of 2' if i % 2 == 0
  //              else 'Multiple of 3' if i % 3 == 0
  //              else i for i in range(1, 20)]
  //   print(my_list)
  //       `,
  //   type: "prog",
  //   level: "easy",
  //   options: [
  //     { id: "1", option: "Displays output in the console" },
  //     { id: "2", option: "Stops the program" },
  //   ],
  //   answer: [{ id: "1" }],
  //   isMultiSelect: false,
  // },
  // {
  //   id: 4,
  //   Ques: "Which of the following is a JavaScript library?",
  //   quesImage: "",
  //   codeBlock: `
  //   my_list = ['Multiple of 6' if i % 6 == 0
  //              else 'Multiple of 2' if i % 2 == 0
  //              else 'Multiple of 3' if i % 3 == 0
  //              else i for i in range(1, 20)]
  //   print(my_list)
  //       `,
  //   type: "prog",
  //   level: "easy",
  //   options: [
  //     { id: "1", option: "React" },
  //     { id: "2", option: "Django" },
  //   ],
  //   answer: [{ id: "1" }],
  //   isMultiSelect: false,
  // },
  // {
  //   id: 5,
  //   Ques: "What does the `for` loop do?",
  //   quesImage: "",
  //   codeBlock: `
  //   my_list = ['Multiple of 6' if i % 6 == 0
  //              else 'Multiple of 2' if i % 2 == 0
  //              else 'Multiple of 3' if i % 3 == 0
  //              else i for i in range(1, 20)]
  //   print(my_list)
  //       `,
  //   type: "prog",
  //   level: "easy",
  //   options: [
  //     { id: "1", option: "Repeats a block of code" },
  //     { id: "2", option: "Executes code once" },
  //   ],
  //   answer: [{ id: "1" }],
  //   isMultiSelect: false,
  // },
  // {
  //   id: 6,
  //   Ques: "Which of the following is a backend framework?",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "prog",
  //   level: "easy",
  //   options: [
  //     { id: "1", option: "Node.js" },
  //     { id: "2", option: "Bootstrap" },
  //   ],
  //   answer: [{ id: "1" }],
  //   isMultiSelect: false,
  // },
  // {
  //   id: 7,
  //   Ques: "What symbol is used to indicate an ID in CSS?",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "prog",
  //   level: "easy",
  //   options: [
  //     { id: "1", option: "#" },
  //     { id: "2", option: "." },
  //   ],
  //   answer: [{ id: "1" }],
  //   isMultiSelect: false,
  // },
  // {
  //   id: 8,
  //   Ques: "What does the `<script>` tag do in HTML?",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "prog",
  //   level: "easy",
  //   options: [
  //     { id: "1", option: "Links JavaScript code" },
  //     { id: "2", option: "Adds styles" },
  //   ],
  //   answer: [{ id: "1" }],
  //   isMultiSelect: false,
  // },
  // {
  //   id: 9,
  //   Ques: "Which of these is used to create a function in JavaScript?",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "prog",
  //   level: "easy",
  //   options: [
  //     { id: "1", option: "def" },
  //     { id: "2", option: "function" },
  //   ],
  //   answer: [{ id: "2" }],
  //   isMultiSelect: false,
  // },
  // {
  //   id: 10,
  //   Ques: "What is the correct syntax to declare a variable in JavaScript?",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "prog",
  //   level: "easy",
  //   options: [
  //     { id: "1", option: "var x = 10;" },
  //     { id: "2", option: "let x: 10;" },
  //   ],
  //   answer: [{ id: "1" }],
  //   isMultiSelect: false,
  // },
  // // Medium
  // {
  //   id: 11,
  //   Ques: "Which of the following methods can be used to fetch data from an API?",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "prog",
  //   level: "medium",
  //   options: [
  //     { id: "1", option: "fetch()" },
  //     { id: "2", option: "getRequest()" },
  //     { id: "3", option: "AJAX" },
  //   ],
  //   answer: [{ id: "1" }, { id: "3" }],
  //   isMultiSelect: true,
  // },
  // {
  //   id: 12,
  //   Ques: "What is the output of `2 + '2'` in JavaScript?",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "prog",
  //   level: "medium",
  //   options: [
  //     { id: "1", option: "22" },
  //     { id: "2", option: "4" },
  //   ],
  //   answer: [{ id: "1" }],
  //   isMultiSelect: false,
  // },
  // {
  //   id: 13,
  //   Ques: "Which keyword is used to define a constant in JavaScript?",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "prog",
  //   level: "medium",
  //   options: [
  //     { id: "1", option: "const" },
  //     { id: "2", option: "static" },
  //   ],
  //   answer: [{ id: "1" }],
  //   isMultiSelect: false,
  // },
  // {
  //   id: 14,
  //   Ques: "What does the `this` keyword refer to in JavaScript?",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "prog",
  //   level: "medium",
  //   options: [
  //     { id: "1", option: "The current object" },
  //     { id: "2", option: "Global context" },
  //   ],
  //   answer: [{ id: "1" }],
  //   isMultiSelect: false,
  // },
  // {
  //   id: 15,
  //   Ques: "What is the purpose of the `map()` function?",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "prog",
  //   level: "medium",
  //   options: [
  //     { id: "1", option: "Iterate and transform an array" },
  //     { id: "2", option: "Filter an array" },
  //   ],
  //   answer: [{ id: "1" }],
  //   isMultiSelect: false,
  // },
  // {
  //   id: 16,
  //   Ques: "Which of the following is a correct way to create an object in JavaScript?",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "prog",
  //   level: "medium",
  //   options: [
  //     { id: "1", option: "let obj = {};" },
  //     { id: "2", option: "let obj = [];" },
  //     { id: "3", option: "let obj = Object();" },
  //   ],
  //   answer: [{ id: "1" }, { id: "3" }],
  //   isMultiSelect: true,
  // },
  // {
  //   id: 17,
  //   Ques: "Which of the following statements is true about JavaScript promises?",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "prog",
  //   level: "medium",
  //   options: [
  //     { id: "1", option: "Promises handle asynchronous operations." },
  //     {
  //       id: "2",
  //       option:
  //         "Promises can be in three states: pending, fulfilled, rejected.",
  //     },
  //     { id: "3", option: "Promises block the main thread." },
  //   ],
  //   answer: [{ id: "1" }, { id: "2" }],
  //   isMultiSelect: true,
  // },
  // {
  //   id: 18,
  //   Ques: "What is the result of `typeof NaN` in JavaScript?",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "prog",
  //   level: "medium",
  //   options: [
  //     { id: "1", option: "number" },
  //     { id: "2", option: "NaN" },
  //     { id: "3", option: "undefined" },
  //   ],
  //   answer: [{ id: "1" }],
  //   isMultiSelect: false,
  // },
  // {
  //   id: 19,
  //   Ques: "Which method is used to combine two or more arrays in JavaScript?",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "prog",
  //   level: "medium",
  //   options: [
  //     { id: "1", option: "concat()" },
  //     { id: "2", option: "merge()" },
  //   ],
  //   answer: [{ id: "1" }],
  //   isMultiSelect: false,
  // },
  // {
  //   id: 20,
  //   Ques: "Which event is triggered when an input field loses focus?",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "prog",
  //   level: "medium",
  //   options: [
  //     { id: "1", option: "blur" },
  //     { id: "2", option: "change" },
  //     { id: "3", option: "focusout" },
  //   ],
  //   answer: [{ id: "1" }, { id: "3" }],
  //   isMultiSelect: true,
  // },
  // // hard
  // {
  //   id: 21,
  //   Ques: "In JavaScript, which of the following methods can cause the loss of the 'this' context in a function?",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "prog",
  //   level: "hard",
  //   options: [
  //     { id: "1", option: "setTimeout()" },
  //     { id: "2", option: "bind()" },
  //     { id: "3", option: "call()" },
  //     { id: "4", option: "apply()" },
  //   ],
  //   answer: [{ id: "1" }],
  //   isMultiSelect: false,
  // },
  // {
  //   id: 22,
  //   Ques: "What will be the output of the following JavaScript code snippet?\n\nconsole.log(0.1 + 0.2 === 0.3);",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "prog",
  //   level: "hard",
  //   options: [
  //     { id: "1", option: "true" },
  //     { id: "2", option: "false" },
  //     { id: "3", option: "NaN" },
  //     { id: "4", option: "undefined" },
  //   ],
  //   answer: [{ id: "2" }],
  //   isMultiSelect: false,
  // },
  // {
  //   id: 23,
  //   Ques: "In Node.js, which of the following modules is used to create HTTP servers?",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "prog",
  //   level: "hard",
  //   options: [
  //     { id: "1", option: "http" },
  //     { id: "2", option: "https" },
  //     { id: "3", option: "fs" },
  //     { id: "4", option: "url" },
  //   ],
  //   answer: [{ id: "1" }],
  //   isMultiSelect: false,
  // },
  // {
  //   id: 24,
  //   Ques: "Which of the following JavaScript features can be used to handle asynchronous operations?",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "prog",
  //   level: "hard",
  //   options: [
  //     { id: "1", option: "Promises" },
  //     { id: "2", option: "async/await" },
  //     { id: "3", option: "setTimeout" },
  //     { id: "4", option: "all of the above" },
  //   ],
  //   answer: [{ id: "4" }],
  //   isMultiSelect: true,
  // },
  // {
  //   id: 25,
  //   Ques: "Which of the following will correctly create a shallow copy of an object in JavaScript?",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "prog",
  //   level: "hard",
  //   options: [
  //     { id: "1", option: "Object.create()" },
  //     { id: "2", option: "Object.assign()" },
  //     { id: "3", option: "JSON.parse(JSON.stringify())" },
  //     { id: "4", option: "Array.from()" },
  //   ],
  //   answer: [{ id: "2" }],
  //   isMultiSelect: false,
  // },
  // {
  //   id: 26,
  //   Ques: "What is the main difference between `null` and `undefined` in JavaScript?",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "prog",
  //   level: "hard",
  //   options: [
  //     { id: "1", option: "`null` is a type, `undefined` is a value" },
  //     {
  //       id: "2",
  //       option: "`null` is an object, `undefined` is a primitive value",
  //     },
  //     {
  //       id: "3",
  //       option:
  //         "`undefined` is used to indicate an intentional absence of value",
  //     },
  //     { id: "4", option: "There is no difference" },
  //   ],
  //   answer: [{ id: "2" }, { id: "3" }],
  //   isMultiSelect: true,
  // },
  // {
  //   id: 27,
  //   Ques: "Which of the following statements about `Event Loop` in JavaScript is true?",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "prog",
  //   level: "hard",
  //   options: [
  //     {
  //       id: "1",
  //       option: "It handles both synchronous and asynchronous operations",
  //     },
  //     { id: "2", option: "It executes code in parallel" },
  //     { id: "3", option: "It processes only synchronous operations" },
  //     { id: "4", option: "It runs in the background indefinitely" },
  //   ],
  //   answer: [{ id: "1" }],
  //   isMultiSelect: false,
  // },
  // {
  //   id: 28,
  //   Ques: "In which of the following scenarios will a JavaScript `setTimeout()` function execute immediately?",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "prog",
  //   level: "hard",
  //   options: [
  //     { id: "1", option: "When the delay is set to 0" },
  //     { id: "2", option: "When the delay is set to 1" },
  //     { id: "3", option: "When the delay is set to infinity" },
  //     { id: "4", option: "When the delay is set to 1000 ms" },
  //   ],
  //   answer: [{ id: "1" }],
  //   isMultiSelect: false,
  // },
  // {
  //   id: 29,
  //   Ques: "Which of the following statements about the `this` keyword in JavaScript is false?",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "prog",
  //   level: "hard",
  //   options: [
  //     {
  //       id: "1",
  //       option: "`this` refers to the global object inside a regular function",
  //     },
  //     { id: "2", option: "`this` is undefined in arrow functions" },
  //     {
  //       id: "3",
  //       option: "`this` refers to the object that invoked the function",
  //     },
  //     { id: "4", option: "`this` can never be manually bound in JavaScript" },
  //   ],
  //   answer: [{ id: "4" }],
  //   isMultiSelect: false,
  // },
  // {
  //   id: 30,
  //   Ques: "Which of the following JavaScript methods can be used to resolve a promise?",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "prog",
  //   level: "hard",
  //   options: [
  //     { id: "1", option: "resolve()" },
  //     { id: "2", option: "reject()" },
  //     { id: "3", option: "then()" },
  //     { id: "4", option: "finally()" },
  //   ],
  //   answer: [{ id: "1" }],
  //   isMultiSelect: false,
  // },
  // LOGICAL
  {
    id: 27,
    Ques: "Tanya is older than Eric. Cliff is older than Tanya. Eric is older than Cliff. If the first two statements are true, the third statement is:",
    quesImage: "",
    codeBlock: "",
    type: "logical",
    level: "easy",
    options: [
      { id: "1", option: "True" },
      { id: "2", option: "False" },
      { id: "3", option: "Uncertain" },
    ],
    answer: [{ id: "2" }],
    isMultiSelect: false,
  },
  {
    id: 28,
    Ques: "Five persons A, B, C, D, and E are sitting in a row facing you... If E occupies a corner position, then who is sitting in the centre?",
    quesImage: "",
    codeBlock: "",
    type: "logical",
    level: "medium",
    options: [
      { id: "1", option: "A" },
      { id: "2", option: "B" },
      { id: "3", option: "C" },
      { id: "4", option: "D" },
      { id: "5", option: "E" },
    ],
    answer: [{ id: "4" }],
    isMultiSelect: false,
  },
  {
    id: 29,
    Ques: "Find the missing number in the sequence: 2, 6, 12, 20, __, 42",
    quesImage: "",
    codeBlock: "",
    type: "logical",
    level: "easy",
    options: [
      { id: "1", option: "30" },
      { id: "2", option: "32" },
      { id: "3", option: "36" },
      { id: "4", option: "40" },
    ],
    answer: [{ id: "1" }],
    isMultiSelect: false,
  },
  {
    id: 30,
    Ques: "",
    quesImage: "",
    codeBlock: `
Statements:  
    All cats are dogs.  
    Some dogs are birds.  

Conclusions:  
    I. Some cats are birds.  
    II. All birds are cats.
`,
    type: "logical",
    level: "easy",
    options: [
      { id: "1", option: "Only Conclusion I follows" },
      { id: "2", option: "Only Conclusion II follows" },
      { id: "3", option: "Both follow" },
      { id: "4", option: "Neither follows" },
    ],
    answer: [{ id: "4" }],
    isMultiSelect: false,
  },
  {
    id: 31,
    Ques: "If MIRROR is coded as NJSQPS, how is WINDOW coded?",
    quesImage: "",
    codeBlock: "",
    type: "logical",
    level: "easy",
    options: [
      { id: "1", option: "XKOEPQ" },
      { id: "2", option: "XJMQPX" },
      { id: "3", option: "XKNPQY" },
      { id: "4", option: "XJOCPX" },
    ],
    answer: [{ id: "4" }],
    isMultiSelect: false,
  },
  {
    id: 32,
    Ques: "A is the father of B. C is the daughter of B. D is the brother of C. How is D related to A?",
    quesImage: "",
    codeBlock: "",
    type: "logical",
    level: "medium",
    options: [
      { id: "1", option: "Son" },
      { id: "2", option: "Grandson" },
      { id: "3", option: "Nephew" },
      { id: "4", option: "Cousin" },
    ],
    answer: [{ id: "2" }],
    isMultiSelect: false,
  },
  {
    id: 33,
    Ques: "10 coaches of a passenger train have got derailed and have blocked the railway track from both ends. ",
    quesImage: "",
    codeBlock: `
    Courses of action:  
        I. The railway authorities should immediately send men and equipment and clear the spot.  
        II. All the trains running in both directions should be diverted immediately via other routes.
      `,
    type: "logical",
    level: "easy",
    options: [
      { id: "1", option: "If only I follows" },
      { id: "2", option: "If only II follows" },
      { id: "3", option: "If either I or II follows" },
      { id: "4", option: "If neither I nor II follows" },
      { id: "5", option: "If both I and II follow" },
    ],
    answer: [{ id: "5" }],
    isMultiSelect: false,
  },
  {
    id: 34,
    Ques: "If PINK is coded as 1691411, then RED will be coded as -",
    quesImage: "",
    codeBlock: "",
    type: "logical",
    level: "easy",
    options: [
      { id: "1", option: "1963" },
      { id: "2", option: "1854" },
      { id: "3", option: "1853" },
      { id: "4", option: "1954" },
    ],
    answer: [{ id: "2" }],
    isMultiSelect: false,
  },
  {
    id: 35,
    Ques: "At the baseball game, Henry was sitting in seat 253. Marla was sitting to the right of Henry in seat 254. In the seat to the left of Henry was George. Inez was sitting to the left of George. Which seat is Inez sitting in?",
    quesImage: "",
    codeBlock: "",
    type: "logical",
    level: "medium",
    options: [
      { id: "1", option: "251" },
      { id: "2", option: "254" },
      { id: "3", option: "255" },
      { id: "4", option: "256" },
    ],
    answer: [{ id: "1" }],
    isMultiSelect: false,
  },
  {
    id: 36,
    Ques: "Select three figures out of the following five figures which when fitted into each other would form a square.",
    quesImage:
      "https://images.javatpoint.com/reasoning/images/construction-of-shapes-q1.png",
    codeBlock: `
  Images of five figures (1, 2, 3, 4, 5) are provided. The goal is to identify which combination of figures, when fitted into each other, forms a square.
    `,
    type: "logical",
    level: "hard",
    options: [
      { id: "1", option: "1, 2, 4" },
      { id: "2", option: "1, 2, 5" },
      { id: "3", option: "5, 3, 1" },
      { id: "4", option: "2, 3, 4" },
    ],
    answer: [{ id: "2" }],
    isMultiSelect: false,
  },
  {
    id: 37,
    Ques: "Which of the following series of figures follows the given rule? Rule: The closed figure loses its sides, and the open figure gains its sides as the series proceeds.",
    quesImage:
      "https://images.javatpoint.com/reasoning/images/rule-detection-q1.png",
    codeBlock: "",
    type: "logical",
    level: "hard",
    options: [
      { id: "1", option: "1" },
      { id: "2", option: "2" },
      { id: "3", option: "3" },
      { id: "4", option: "4" },
    ],
    answer: [{ id: "1" }],
    isMultiSelect: false,
  },
  {
    id: 38,
    Ques: "  Peter is in the East of Tom and Tom is in the North of John. Mike is in the South of John then in which direction of Peter is Mike?",
    codeBlock: "",
    type: "logical",
    level: "medium",
    options: [
      { id: "1", option: "South-East" },
      { id: "2", option: "South-West" },
      { id: "3", option: "South" },
      { id: "4", option: "North-East" },
    ],
    answer: [{ id: "1" }],
    isMultiSelect: false,
  },
  {
    id: 39,
    Ques: "P and Q are the married couple. X and Y are sisters. X is the sister of P. How is Y related to Q?",
    codeBlock: "",
    type: "logical",
    level: "medium",
    options: [
      { id: "1", option: "Sister" },
      { id: "2", option: "Cousin" },
      { id: "3", option: "Sister-in-law" },
      { id: "4", option: "Daughter-in-law" },
    ],
    answer: [{ id: "3" }],
    isMultiSelect: false,
  },
  {
    id: 40,
    Ques: "Count the number of rectangles in the below figure.",
    quesImage:
      "https://media.geeksforgeeks.org/wp-content/uploads/20230911093322/Analytical-reasoning-(20-images)-07.webp",
    codeBlock: "",
    type: "logical",
    level: "hard",
    options: [
      { id: "1", option: "19" },
      { id: "2", option: "16" },
      { id: "3", option: "30" },
      { id: "4", option: "34" },
    ],
    answer: [{ id: "4" }],
    isMultiSelect: false,
  },
  // {
  //   id: 31,
  //   Ques: "Which number logically completes the series: 2, 5, 10, 17, __ ?",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "logical",
  //   level: "easy",
  //   options: [
  //     { id: "1", option: "26" },
  //     { id: "2", option: "20" },
  //     { id: "3", option: "23" },
  //     { id: "4", option: "30" },
  //   ],
  //   answer: [{ id: "1" }],
  //   isMultiSelect: false,
  // },
  // {
  //   id: 32,
  //   Ques: "If all roses are flowers, and all flowers are plants, which of the following statements is true?",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "logical",
  //   level: "easy",
  //   options: [
  //     { id: "1", option: "All roses are plants" },
  //     { id: "2", option: "All plants are roses" },
  //     { id: "3", option: "Some plants are roses" },
  //     { id: "4", option: "No roses are plants" },
  //   ],
  //   answer: [{ id: "1" }],
  //   isMultiSelect: false,
  // },
  // {
  //   id: 33,
  //   Ques: "Which of the following is the odd one out?",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "logical",
  //   level: "medium",
  //   options: [
  //     { id: "1", option: "Cat" },
  //     { id: "2", option: "Dog" },
  //     { id: "3", option: "Elephant" },
  //     { id: "4", option: "Tiger" },
  //   ],
  //   answer: [{ id: "3" }],
  //   isMultiSelect: false,
  // },
  // {
  //   id: 34,
  //   Ques: "Find the next number in the series: 3, 6, 12, 24, __ ?",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "logical",
  //   level: "medium",
  //   options: [
  //     { id: "1", option: "48" },
  //     { id: "2", option: "36" },
  //     { id: "3", option: "60" },
  //     { id: "4", option: "72" },
  //   ],
  //   answer: [{ id: "1" }],
  //   isMultiSelect: false,
  // },
  // {
  //   id: 35,
  //   Ques: "If the day before yesterday was a Thursday, what day will it be 10 days after the day after tomorrow?",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "logical",
  //   level: "medium",
  //   options: [
  //     { id: "1", option: "Saturday" },
  //     { id: "2", option: "Sunday" },
  //     { id: "3", option: "Friday" },
  //     { id: "4", option: "Thursday" },
  //   ],
  //   answer: [{ id: "2" }],
  //   isMultiSelect: false,
  // },
  // {
  //   id: 36,
  //   Ques: "Which of the following logically follows the sequence: 1, 4, 9, 16, __ ?",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "logical",
  //   level: "hard",
  //   options: [
  //     { id: "1", option: "25" },
  //     { id: "2", option: "20" },
  //     { id: "3", option: "18" },
  //     { id: "4", option: "27" },
  //   ],
  //   answer: [{ id: "1" }],
  //   isMultiSelect: false,
  // },
  // {
  //   id: 37,
  //   Ques: "Which number logically completes the series: 1, 1, 2, 6, 24, __ ?",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "logical",
  //   level: "hard",
  //   options: [
  //     { id: "1", option: "120" },
  //     { id: "2", option: "100" },
  //     { id: "3", option: "150" },
  //     { id: "4", option: "180" },
  //   ],
  //   answer: [{ id: "1" }],
  //   isMultiSelect: false,
  // },
  // {
  //   id: 38,
  //   Ques: "In a certain code language, 'BASKET' is written as 'RAVXBG'. How would you write 'RACKET' in the same code language?",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "logical",
  //   level: "hard",
  //   options: [
  //     { id: "1", option: "RAVXBG" },
  //     { id: "2", option: "ZSDXHV" },
  //     { id: "3", option: "DGLJHM" },
  //     { id: "4", option: "RAVYBG" },
  //   ],
  //   answer: [{ id: "2" }],
  //   isMultiSelect: false,
  // },
  // {
  //   id: 39,
  //   Ques: "In a race, you overtake the person who is second. What position are you in now?",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "logical",
  //   level: "hard",
  //   options: [
  //     { id: "1", option: "First" },
  //     { id: "2", option: "Second" },
  //     { id: "3", option: "Third" },
  //     { id: "4", option: "Fourth" },
  //   ],
  //   answer: [{ id: "1" }],
  //   isMultiSelect: false,
  // },
  // {
  //   id: 40,
  //   Ques: "Which one of the following does not belong to the group?",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "logical",
  //   level: "hard",
  //   options: [
  //     { id: "1", option: "Square" },
  //     { id: "2", option: "Rectangle" },
  //     { id: "3", option: "Circle" },
  //     { id: "4", option: "Triangle" },
  //   ],
  //   answer: [{ id: "3" }],
  //   isMultiSelect: false,
  // },
  // QUANTS
  {
    id: 41,
    Ques: "A person has 4 coins each of different denominations. What is the number of different sums of money the person can form (using one or more coins at a time)?",
    quesImage: "",
    codeBlock: "",
    type: "quants",
    level: "medium",
    options: [
      { id: "1", option: "15" },
      { id: "2", option: "16" },
      { id: "3", option: "12" },
      { id: "4", option: "11" },
    ],
    answer: [{ id: "1" }],
    isMultiSelect: false,
  },
  {
    id: 42,
    Ques: "If (2x - y) = 4 then (6x - 3y) =?",
    quesImage: "",
    codeBlock: "",
    type: "quants",
    level: "easy",
    options: [
      { id: "1", option: "15" },
      { id: "2", option: "12" },
      { id: "3", option: "18" },
      { id: "4", option: "10" },
    ],
    answer: [{ id: "2" }],
    isMultiSelect: false,
  },
  {
    id: 43,
    Ques: "A, B and C jointly thought of starting a business venture. It was agreed that A would invest Rs. 6500 for 6 months, B, Rs. 9100 for 5 months and C, Rs. 13,000 for 3 months. A wants to be the working member for which, he was to receive 5% of the profits. The profit earned was Rs. 8000. Calculate the share of B in the profit.",
    quesImage: "",
    codeBlock: "",
    type: "quants",
    level: "medium",
    options: [
      { id: "1", option: "Rs. 1900" },
      { id: "2", option: "Rs. 2660" },
      { id: "3", option: "Rs. 2800" },
      { id: "4", option: "Rs. 2840" },
    ],
    answer: [{ id: "3" }],
    isMultiSelect: false,
  },
  {
    id: 44,
    Ques: "A cow is tethered in the middle of the field with a 14-foot-long rope. If the cow grazes 100 sq. ft. per day, then approximately what time will be taken by the cow to graze the whole field? (Approx)",
    quesImage: "",
    codeBlock: "",
    type: "quants",
    level: "hard",
    options: [
      { id: "1", option: "2 days" },
      { id: "2", option: "6.15 days" },
      { id: "3", option: "18.5 days" },
      { id: "4", option: "24 days" },
      { id: "5", option: "None of these" },
    ],
    answer: [{ id: "2" }],
    isMultiSelect: false,
  },
  {
    id: 45,
    Ques: "A man travelled 30% of his journey at a speed of 85 kmph and the rest of his journey at a speed of 33 kmph. Find his average speed throughout the journey.",
    quesImage: "",
    codeBlock: "",
    type: "quants",
    level: "medium",
    options: [
      { id: "1", option: "46.6 kmph" },
      { id: "2", option: "48.6 kmph" },
      { id: "3", option: "42.6 kmph" },
      { id: "4", option: "44.6 kmph" },
    ],
    answer: [{ id: "2" }],
    isMultiSelect: false,
  },
  {
    id: 46,
    Ques: "A shopkeeper sold an article for Rs. 2500. If the cost price of the article is 2000, find the profit percent.",
    quesImage: "",
    codeBlock: "",
    type: "quants",
    level: "easy",
    options: [
      { id: "1", option: "23%" },
      { id: "2", option: "25%" },
      { id: "3", option: "27%" },
      { id: "4", option: "29%" },
    ],
    answer: [{ id: "2" }],
    isMultiSelect: false,
  },
  {
    id: 47,
    Ques: "In a 500 m race, the ratio of the speeds of two participants A and B is 3:4. A has a start of 140 m. Then, A wins by?",
    quesImage: "",
    codeBlock: "",
    type: "quants",
    level: "medium",
    options: [
      { id: "1", option: "60m" },
      { id: "2", option: "40m" },
      { id: "3", option: "20m" },
      { id: "4", option: "10m" },
    ],
    answer: [{ id: "3" }],
    isMultiSelect: false,
  },
  {
    id: 48,
    Ques: "What is the probability of getting an even number when a dice is rolled?",
    quesImage: "",
    codeBlock: "",
    type: "quants",
    level: "easy",
    options: [
      { id: "1", option: "1/5" },
      { id: "2", option: "1/2" },
      { id: "3", option: "1/3" },
      { id: "4", option: "1/4" },
    ],
    answer: [{ id: "2" }],
    isMultiSelect: false,
  },
  {
    id: 49,
    Ques: "To complete a work, a person A takes 10 days and another person B takes 15 days. If they work together, in how much time will they complete the work?",
    quesImage: "",
    codeBlock: "",
    type: "quants",
    level: "easy",
    options: [
      { id: "1", option: "5 days" },
      { id: "2", option: "6 days" },
      { id: "3", option: "7 days" },
      { id: "4", option: "4 days" },
    ],
    answer: [{ id: "2" }],
    isMultiSelect: false,
  },
  {
    id: 50,
    Ques: "Two friends A and B working together can complete an assignment in 4 days. If A can do the assignment alone in 12 days, in how many days can B alone do the assignment?",
    quesImage: "",
    codeBlock: "",
    type: "quants",
    level: "easy",
    options: [
      { id: "1", option: "4 days" },
      { id: "2", option: "5 days" },
      { id: "3", option: "6 days" },
      { id: "4", option: "7 days" },
    ],
    answer: [{ id: "3" }],
    isMultiSelect: false,
  },
  {
    id: 51,
    Ques: "A bank provides a loan of ₹55,000 to a shopkeeper at a 5% compound rate of interest (Compounded annually). After 2 years the amount to be deposited by the shopkeeper is:",
    quesImage: "",
    codeBlock: "",
    type: "quants",
    level: "hard",
    options: [
      { id: "1", option: "₹62,526.50" },
      { id: "2", option: "₹65,259.75" },
      { id: "3", option: "₹60,637.50" },
      { id: "4", option: "₹55,825.75" },
    ],
    answer: [{ id: "3" }],
    isMultiSelect: false,
  },
  {
    id: 52,
    Ques: "Which of the following is a prime number?",
    quesImage: "",
    codeBlock: "",
    type: "quants",
    level: "medium",
    options: [
      { id: "1", option: "517" },
      { id: "2", option: "559" },
      { id: "3", option: "571" },
      { id: "4", option: "533" },
    ],
    answer: [{ id: "3" }],
    isMultiSelect: false,
  },
  {
    id: 53,
    Ques: "In a class, the ratio of boys to girls is 5:3. If there are 40 boys, how many girls are there in the class?",
    quesImage: "",
    codeBlock: "",
    type: "quants",
    level: "easy",
    options: [
      { id: "1", option: "22 girls" },
      { id: "2", option: "24 girls" },
      { id: "3", option: "23 girls" },
      { id: "4", option: "25 girls" },
    ],
    answer: [{ id: "2" }],
    isMultiSelect: false,
  },
  {
    id: 54,
    Ques: "If a person can complete a task in 8 hours, how much of the task can they complete in 2 hours?",
    quesImage: "",
    codeBlock: "",
    type: "quants",
    level: "easy",
    options: [
      { id: "1", option: "2/3 task" },
      { id: "2", option: "1/4 task" },
      { id: "3", option: "1 task" },
      { id: "4", option: "1/3 task" },
    ],
    answer: [{ id: "2" }],
    isMultiSelect: false,
  },
  {
    id: 55,
    Ques: "A and B take part in a 100 m race. A runs at 5 km per hour. A gives B a start of 8 m and still beats him by 8 seconds. The speed of B is:",
    quesImage: "",
    codeBlock: "",
    type: "quants",
    level: "medium",
    options: [
      { id: "1", option: "5.15 km/hr" },
      { id: "2", option: "4.14 km/hr" },
      { id: "3", option: "4.25 km/hr" },
      { id: "4", option: "4.41 km/hr" },
    ],
    answer: [{ id: "2" }],
    isMultiSelect: false,
  },
  {
    id: 56,
    Ques: "A drum of water is 2/5 full. When 38 liters are drawn from it, it is just 1/8 full. Find the total capacity of the drum in liters.",
    quesImage: "",
    codeBlock: "",
    type: "quants",
    level: "medium",
    options: [
      { id: "1", option: "135" },
      { id: "2", option: "137" },
      { id: "3", option: "138" },
      { id: "4", option: "140" },
    ],
    answer: [{ id: "3" }],
    isMultiSelect: false,
  },
  // {
  //   id: 41,
  //   Ques: "What is the value of 15% of 250?",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "quants",
  //   level: "easy",
  //   options: [
  //     { id: "1", option: "30" },
  //     { id: "2", option: "40" },
  //     { id: "3", option: "50" },
  //     { id: "4", option: "60" },
  //   ],
  //   answer: [{ id: "1" }],
  //   isMultiSelect: false,
  // },
  // {
  //   id: 42,
  //   Ques: "If a car travels 120 kilometers in 2 hours, what is its average speed?",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "quants",
  //   level: "easy",
  //   options: [
  //     { id: "1", option: "60 km/h" },
  //     { id: "2", option: "50 km/h" },
  //     { id: "3", option: "70 km/h" },
  //     { id: "4", option: "80 km/h" },
  //   ],
  //   answer: [{ id: "1" }],
  //   isMultiSelect: false,
  // },
  // {
  //   id: 43,
  //   Ques: "What is the least common multiple (LCM) of 6, 8, and 12?",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "quants",
  //   level: "medium",
  //   options: [
  //     { id: "1", option: "24" },
  //     { id: "2", option: "36" },
  //     { id: "3", option: "48" },
  //     { id: "4", option: "60" },
  //   ],
  //   answer: [{ id: "1" }],
  //   isMultiSelect: false,
  // },
  // {
  //   id: 44,
  //   Ques: "If a box contains 5 red balls, 7 green balls, and 3 blue balls, what is the probability of drawing a red ball?",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "quants",
  //   level: "medium",
  //   options: [
  //     { id: "1", option: "5/15" },
  //     { id: "2", option: "7/15" },
  //     { id: "3", option: "3/15" },
  //     { id: "4", option: "1/3" },
  //   ],
  //   answer: [{ id: "1" }],
  //   isMultiSelect: false,
  // },
  // {
  //   id: 45,
  //   Ques: "A man can complete a task in 5 days. How long will it take him to complete the task if he works at half the speed?",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "quants",
  //   level: "medium",
  //   options: [
  //     { id: "1", option: "10 days" },
  //     { id: "2", option: "15 days" },
  //     { id: "3", option: "20 days" },
  //     { id: "4", option: "25 days" },
  //   ],
  //   answer: [{ id: "1" }],
  //   isMultiSelect: false,
  // },
  // {
  //   id: 46,
  //   Ques: "Which of the following numbers is a prime number?",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "quants",
  //   level: "hard",
  //   options: [
  //     { id: "1", option: "29" },
  //     { id: "2", option: "30" },
  //     { id: "3", option: "32" },
  //     { id: "4", option: "35" },
  //   ],
  //   answer: [{ id: "1" }],
  //   isMultiSelect: false,
  // },
  // {
  //   id: 47,
  //   Ques: "What is the square root of 144?",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "quants",
  //   level: "hard",
  //   options: [
  //     { id: "1", option: "10" },
  //     { id: "2", option: "12" },
  //     { id: "3", option: "14" },
  //     { id: "4", option: "16" },
  //   ],
  //   answer: [{ id: "2" }],
  //   isMultiSelect: false,
  // },
  // {
  //   id: 48,
  //   Ques: "The cost of 5 apples is $15. What is the cost of 8 apples?",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "quants",
  //   level: "hard",
  //   options: [
  //     { id: "1", option: "$24" },
  //     { id: "2", option: "$30" },
  //     { id: "3", option: "$40" },
  //     { id: "4", option: "$45" },
  //   ],
  //   answer: [{ id: "1" }],
  //   isMultiSelect: false,
  // },
  // {
  //   id: 49,
  //   Ques: "If the probability of an event happening is 3/5, what is the probability of the event not happening?",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "quants",
  //   level: "hard",
  //   options: [
  //     { id: "1", option: "2/5" },
  //     { id: "2", option: "3/5" },
  //     { id: "3", option: "1/5" },
  //     { id: "4", option: "4/5" },
  //   ],
  //   answer: [{ id: "1" }],
  //   isMultiSelect: false,
  // },
  // {
  //   id: 50,
  //   Ques: "Which of the following pairs are equal?",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "quants",
  //   level: "hard",
  //   options: [
  //     { id: "1", option: "4 : 2" },
  //     { id: "2", option: "9 : 3" },
  //     { id: "3", option: "16 : 4" },
  //     { id: "4", option: "25 : 5" },
  //   ],
  //   answer: [{ id: "1" }, { id: "4" }],
  //   isMultiSelect: true,
  // },
  // {
  //   id: 51,
  //   Ques: "Which of the following are prime numbers?",
  //   quesImage: "",
  //   codeBlock: "",
  //   type: "quants",
  //   level: "hard",
  //   options: [
  //     { id: "1", option: "17" },
  //     { id: "2", option: "21" },
  //     { id: "3", option: "19" },
  //     { id: "4", option: "22" },
  //   ],
  //   answer: [{ id: "1" }, { id: "3" }],
  //   isMultiSelect: true,
  // },
];

module.exports = Questions;
